#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)/frontend"
echo "🔍 Проверка типов TypeScript..."
bun run type-check

echo "🧹 Проверка линтинга..."
bun run lint

echo "🏗️ Проверка сборки..."
bun run build